### ISSUE TITLE
HDFView does not visualize image data from non-scalar plugin features written to an .rtdc file with RTDCWriter

### ISSUE THREAD

**Issue by RaghavaAlajangi** [DC-analysis/dclab#171]
When a user tries to save a new image plugin feature with a 2D or 3D array using `RTDCWriter.store_feature()`, it simply saves the data as an array without image attributes. Due to this, the HDFView application is not recognizing this feature as an image. Thus, in order to solve this, image attributes should be added while saving the image data as a plugin feature.

<img src="https://user-images.githubusercontent.com/48808595/171859552-27640875-9e2d-44f3-b345-c3ea9a78d7b9.png" width="70%">

<img src="https://user-images.githubusercontent.com/48808595/171859800-6099b7ab-5c3a-47b3-a00c-73175f48bfcb.png" width="70%">

**Comment by paulmueller** [comment]
Thanks for starting this issue. In our previous conversation, you referred to the HDF5 dataset attributes that make HDFView recognize 2D data as images, i.e.

https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/0.40.0/dclab/rtdc_dataset/writer.py#L385-L391

I think it makes sense to to have this as a default in `write_ndarray` for all 2D features.

**Comment by RaghavaAlajangi** [comment]
Yes, but, what if there would be a new feature like contour data (x and y coordinates > 2D array). It should not be an image, right?

**Comment by paulmueller** [comment]
That's correct. Maybe it makes sense to have a minimum size of each dimension of e.g. 3?

**Comment by RaghavaAlajangi** [comment]
Yes, if HDFView was able to do that, that would be great.

**Comment by PinkShnack** [comment]
> On the other hand, it only affects HDFView. If HDFView is capable of plotting (e.g. contours), then we should definitely add the corresponding attributes.

afaik, HDFView can't visualise contour data.

**Comment by RaghavaAlajangi** [comment]
> On the other hand, it only affects HDFView. If HDFView is capable of plotting (e.g. contours), then we should definitely add the corresponding attributes.

Yes, it is only affecting the HDFView. I saved contour data as an image in a sample `.hdf5` file and opened it in HDFView. Because of attributes, it showed as an image (straight line) but we can access it as a NumPy array. So, what can we do here? save all 2D arrays as images?

**Comment by paulmueller** [comment]
> > On the other hand, it only affects HDFView. If HDFView is capable of plotting (e.g. contours), then we should definitely add the corresponding attributes.
> 
> Yes, it is only affecting the HDFView. I saved contour data as an image in a sample `.hdf5` file and opened it in HDFView. Because of attributes, it showed as an image (straight line) but we can access it as a NumPy array. So, what can we do here? save all 2D arrays as images?

Maybe only for 2D arrays where both dimensions have a size larger than 3?

**Comment by RaghavaAlajangi** [comment]
I made corresponding changes and created a merge request. Please have a look (@paulmueller and @PinkShnack) and let me know if it needs any further changes.

**Comment by PinkShnack** [comment]
> Please have a look

You should link this issue with the Merge Request.

**Comment by RaghavaAlajangi** [comment]
@paulmueller we have another problem with contour data. What if we want to save contour data as a plugin feature (with shape --> (len, nan, 2)), then dimension check is not sufficient because we have 'nan' type in contour. Instead, can we use plugin info (ex "features required") to decide the type of feature?

**Comment by PinkShnack** [comment]
> @paulmueller we have another problem with contour data. What if we want to save contour data as a plugin feature (with shape --> (len, nan, 2)), then dimension check is not sufficient because we have 'nan' type in contour. Instead, can we use plugin info (ex "features required") to decide the type of feature?

Is this included in a test as an example? If so, link the test here.

**Comment by RaghavaAlajangi** [comment]
I haven't committed yet. I am testing locally. Do you want me to merge the changes?
