### ISSUE TITLE
Describe the caveats of using `ds.filter` in the docs

### ISSUE THREAD

**Issue by PinkShnack** [DC-analysis/dclab#173]
I was recently designing a tool that used `ds.filter.all`/`ds.filter.manual`/`ds.apply_filter()` etc. There was some behaviour that I did not expect. This behaviour should be described in the documentation for users.

### Example confusing Situation
- Description:
   - When setting several events `False` via `ds.filter.manual`, these events were not set to `False` after calling `ds.apply_filter()`. This was due to previously calling a filter via `ds.config['filtering']`. This makes sense. However, I thought that after calling the initial `ds.config['filtering']`, using `ds.reset_filter()` would have totally reset the filter to True and allowed me to work with it cleanly. However, reset in this case didn't do as I expected. My final solution was to initially create a child, call `ds.config['filtering']`, and then use the parent later on for the manual filter.
- Order of calls:
   - `ds.config['filtering']`
   - `ds.apply_filter()`
   - `ds.reset_filter()`  # aim is to set all events back to True
   - `ds.filter.manual`  # set 2 events manually to False
   - Create `ds_child`. Should be the length of `ds` - 2.
- Possible Issue/Solution:
   - [ ] So either I don't understand what `ds.reset_filter()` does, or how the `ds_child` is created.
   - [ ] Could include a simple version of the above situation in the tests to check how these steps should behave.
   - [ ] Whichever is the behaviour, describe it in the docs.
   - [ ] Describe in more places in the docs and docstrings the `ds.filter.manual` and what it should be used for.

**Comment by paulmueller** [comment]
I think the default behavior should be intuitive, so this might be a bug. Could you please provide an example script?

**Comment by PinkShnack** [comment]
> I think the default behavior should be intuitive, so this might be a bug. Could you please provide an example script?

Will do, when I get around to this!

**Comment by felix-r** [comment]
I'd like to reopen this because I think, I just came across the same problems as Eoghan. I want to filter a dataset based on a manual filter I create. But the function `ds.filter.manual` does not seems to help here. To understand how it works I tried the following: I created a filter by using `ds.config['filtering']`:

```python
rtdc_file = "some_file.rtdc"
ds = dclab.new_dataset(rtdc_file)
ds.config['filtering']['area_ratio min'] = 0
ds.config['filtering']['area_ratio max'] = 1.05
ds.apply_filter()
filter_test = ds.filter.all
```

Then `filter_test` should have some `False` entries:

```python
np.all(filter_test)
>>> False
```

Now, I tried to create a new dataset from the same file and apply `filter_test` as a manual filter:

```python
ds_2 = dclab.new_dataset(rtdc_file)
ds_2.filter.manual[filter_test]
ds_2.apply_filter()
```

But then the filter is not really used on `ds_2`, all the values of the filter array are `True`:

```python
np.all(ds_2.filter.all)
>>> True

np.all(ds_2.filter.manual)
>>> True
```

Another way to illustrate it would be:
```python
len(ds['deform']) == len(ds['deform'][filter_test])
>>> False

len(ds_2['deform']) == len(ds_2['deform'][ds_2.filter.all])
>>> True
```
I guess that is not the intended use case. I would expect that `filter.manual` can actually be used to filter the datasets.

**Comment by felix-r** [comment]
BTW I used dclab version 0.43.1

**Comment by paulmueller** [comment]
Did you mean to set `ds_2.filter.manual[filter_test] = False`?

**Comment by felix-r** [comment]
Yes, this is exactly what I want to do. Thanks for clarifying. 

Maybe a short example like this in the documentation could help users to understand how to use the manual filters. I think there was an example included in an earlier version but I couldn't find anything in the stable version of the docs.

**Comment by paulmueller** [comment]
These are the sections in the docs:

https://dclab.readthedocs.io/en/stable/sec_av_rtdc_dataset.html#using-filters
https://dclab.readthedocs.io/en/stable/sec_av_rtdc_dataset.html#creating-hierarchies
