### ISSUE TITLE
Editing logs when exporting rtdc files

### ISSUE THREAD

**Issue by felix-r** [DC-analysis/dclab#180]
When exporting rtdc files via `ds.export.hdf5`, I noticed that the logs don't get exported, even though the dataset contains logs. Furthermore, I would actually like to add an item to the logs and then export it. Is this currently implemented somehow? I could not find how to do it.

**Comment by paulmueller** [comment]
Adding the original logs could be implemented (with a prefix "source_" or so, because the data have been altered).

You can add your own logs with the `RTDCWriter` class. It should work like this:

```python
with dclab.RTDCWriter(filename) as hw:
    hw.store_log(list_of_strings)
```

**Comment by felix-r** [comment]
Thanks, that is helpful. Though, the correct syntax looks like this:

```python
with dclab.RTDCWriter(filename) as hw:
    hw.store_log(log_name, list_of_strings)
```
