### ISSUE TITLE
Update docs on how to access data on a different DCOR server

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/dclab#182]
URLs are as follows:

https://dcor.mpl.mpg.de/api/3/action/dcserv?id=6fd1b41c-7ee4-47e4-93d5-1cc05d4d43d2

**Comment by paulmueller** [comment]
Also change mentioning of "API Key" to "API token" and add information on how to create one in the docs.

**Comment by B-Hartmann** [comment]
Should the keyword argument `api_key` also be changed to `api_token`? For the sake of consistency? For example in the class `RTDC_DCOR`.

**Comment by paulmueller** [comment]
> Should terminology be changed in the code as well, for the sake of consistency? For example, the keyword argument `api_key` changed to `api_token`? For example, in the class `RTDC_DCOR` and in the class `APIHandler`.

Ultimately yes, but this should be tracked in a different issue. The use of `api_key` should properly be deprecated, so downstream code does not immediately break.
